server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yupi
      routes:
          # 定义了一个名为"api_route"的路由规则,该规则将匹配以"/api/"开头的路径,例如"/api/user",
          # 并将这些请求转发到"http://localhost:8123"这个目标地址
          - id: api_route
            uri: http://localhost:8123
            predicates:
              - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qosEnable: true
    qosPort: 22223
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
